Fixed the alignment issue (Issue#10)
Codess-Cafe/Codess-Website pull request #43
Opened 2023-10-19 13:19 UTC by Reene-Simon

Fixed the alignment issue where the social bar, text block and image were at different alignments. According to the instructions given, the text block was centered with respect to the image block and the social bar was aligned accordingly.
![Codess Issue#10](https://github.com/Codess-Cafe/Codess-Website/assets/112744886/745a56f2-f69f-48bd-b340-f753954a3482)

2023-10-20 04:40 UTC, VidhiBhatt01 requested changes
You just had to increase image and move the text box down by few pixels. No need to even touch the socials bar Just think logically, does the alignment in this PR look good?

2023-10-20 10:35 UTC, Reene-Simon commented
![Codess Issue#10 Final](https://github.com/Codess-Cafe/Codess-Website/assets/112744886/1bfccc07-6bb4-4dfb-aa44-9af4837bcc73)
This is the updated version where the changes requested above have been made. The image cannot be increased further as it messes up with the dimensions of the same making it book bad.

2023-10-20 12:55 UTC, VidhiBhatt01 approved these changes

2023-10-20 12:55 UTC, merged

2023-10-21 10:16 UTC, VidhiBhatt01 commented
#10 resolved