Update 'Apply' Section for Formatting and Terminology
Codess-Cafe/Codess-Website pull request #8
Opened 2023-10-15 01:58 UTC by NereidaRondon

Resolves Issue #1

2023-10-15 13:58 UTC, VidhiBhatt01 reviewed
Raise a PR only after the issue is assigned,

PS: The issue is updated

2023-10-15 14:25 UTC, joeyouss commented
@NereidaRondon I will get your PR reviewed and merged if it is correct.

2023-10-15 14:54 UTC, VidhiBhatt01 commented
@NereidaRondon So sorry. There was some internal confusion between we maintainers.

Anyways, I would suggest you that please  comment here once https://github.com/Codess-Cafe/Codess-Website/issues/1 so that we can assign it to you. Also, go through the description once again and update this PR accordingly

2023-10-15 20:05 UTC, NereidaRondon commented
I went ahead and changed the extra requirement that was added to the issue. Hope all is good now. Thank you.

2023-10-16 03:41 UTC, VidhiBhatt01 requested changes
Just update one typo. Rest lgtm

2023-10-16 03:41 UTC, VidhiBhatt01 commented on index.html
> +                    Shortlisted members are contacted via mail, Linkedin or
Linkedin -> LinkedIn

2023-10-16 03:42 UTC, VidhiBhatt01 commented
Also please comment on #1

2023-10-17 17:31 UTC, VidhiBhatt01 approved these changes

2023-10-18 09:43 UTC, merged