All_setup
Codess-Cafe/Codess-Website pull request #97
Opened 2023-10-30 13:38 UTC by Tooba-Amjad

@VidhiBhatt01 
I simply copied the CSS code from the provided section and pasted it. Everything was set up as you requested, and I'm explaining this to you because you asked for some minor changes and requested that I create pull requests individually. However, it was all set up with just one click.

![Screenshot (241)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/a7fe68d0-1803-41be-b5dc-6e70b253b343)

![Screenshot (242)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/076dfc4f-dd5c-434f-96da-740cc4399ee9)

![Screenshot (243)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/42f3b1bf-600e-4774-81ed-acc5120815da)

2023-10-30 14:01 UTC, Tooba-Amjad commented
@VidhiBhatt01 
This is how the complete Site Looks like now
Uploading WhatsApp Video 2023-10-30 at 6.59.50 PM.mp4…

2023-10-30 14:07 UTC, Reene-Simon commented
@VidhiBhatt01 this has brought everything back to its original state. I'm currently working on some of the small details and will make a PR accordingly.

It was a change in the lower portion of the code with regards to the responsiveness which messed up with everything even in the upper part of the website.

2023-10-30 19:00 UTC, VidhiBhatt01 commented on style.css
> +.social-icons i:hover {
this change should not be added in this commit.

2023-10-30 19:03 UTC, VidhiBhatt01 requested changes
Got it thanks for the effort girls. We are still missing some things.

1. Spacing between what do our students say.
2. Updating hover effect on LinkedIn icon.
3. Adding hover effect Rigorous Coding Practice, Regular Mock Interviews icons..


Also, how responsive is the site currently? Can you both make if fully responsive?

2023-10-30 19:05 UTC, VidhiBhatt01 commented
Okay, just saw the other PRs, ig we are sorted then. Fix LinkedIn hover effect and lmk about responsiveness

2023-10-31 01:21 UTC, Reene-Simon commented
@VidhiBhatt01 the LinkedIn hover effect is being handled my Tooba and she has made a PR for the same. As far as responsiveness is concerned, we'll check it out and let uk.

2023-10-31 10:19 UTC, Reene-Simon commented
@VidhiBhatt01 the responsiveness is mostly ok. Just want to check once this PR is merged as the layout is messed up as of now. After this PR is merged I'll give u an update about the same.

2023-10-31 15:42 UTC, closed without merging